Traceback (most recent call last):
  File "/Users/williamthompson/micromamba/envs/openai-helper/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/williamthompson/micromamba/envs/openai-helper/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamthompson/micromamba/envs/openai-helper/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamthompson/micromamba/envs/openai-helper/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/williamthompson/micromamba/envs/openai-helper/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/williamthompson/micromamba/envs/openai-helper/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/williamthompson/micromamba/envs/openai-helper/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
RESUME_ROOT_DIR = os.path.expanduser('~/Documents/resume_data/data/data')
PERSIST_ROOT_DIR = os.path.expanduser('~/Documents/resume_data/persist')

from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader(os.path.join(RESUME_ROOT_DIR,'FITNESS','10428916.pdf'))
pages = loader.load_and_split()

print(pages[0].page_content[:550])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      2[0m RESUME_ROOT_DIR [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mexpanduser([38;5;124m'[39m[38;5;124m~/Documents/resume_data/data/data[39m[38;5;124m'[39m)
[1;32m      3[0m PERSIST_ROOT_DIR [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mexpanduser([38;5;124m'[39m[38;5;124m~/Documents/resume_data/persist[39m[38;5;124m'[39m)
[0;32m----> 5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mlangchain[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdocument_loaders[39;00m [38;5;28;01mimport[39;00m PyPDFLoader
[1;32m      6[0m loader [38;5;241m=[39m PyPDFLoader(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(RESUME_ROOT_DIR,[38;5;124m'[39m[38;5;124mFITNESS[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124m10428916.pdf[39m[38;5;124m'[39m))
[1;32m      7[0m pages [38;5;241m=[39m loader[38;5;241m.[39mload_and_split()

[0;31mModuleNotFoundError[0m: No module named 'langchain'

